# Libraries

In [50]:
import os

import kagglehub
import pandas as pd
from kagglehub import KaggleDatasetAdapter

from src.data_cleaning import cleaning_int_variables

os.chdir("..")

pd.set_option("display.max_columns", None)
pd.options.display.float_format = "{:,.2f}".format
import os

# Data

In [51]:
train_df = kagglehub.load_dataset(
    KaggleDatasetAdapter.PANDAS, "parisrohan/credit-score-classification", "train.csv"
)

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_11754/4040410273.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  train_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(

# Cleaning Numerical Values:

In [52]:
train_df.columns

Index(['ID', 'Customer_ID', 'Month', 'Name', 'Age', 'SSN', 'Occupation',
       'Annual_Income', 'Monthly_Inhand_Salary', 'Num_Bank_Accounts',
       'Num_Credit_Card', 'Interest_Rate', 'Num_of_Loan', 'Type_of_Loan',
       'Delay_from_due_date', 'Num_of_Delayed_Payment', 'Changed_Credit_Limit',
       'Num_Credit_Inquiries', 'Credit_Mix', 'Outstanding_Debt',
       'Credit_Utilization_Ratio', 'Credit_History_Age',
       'Payment_of_Min_Amount', 'Total_EMI_per_month',
       'Amount_invested_monthly', 'Payment_Behaviour', 'Monthly_Balance',
       'Credit_Score'],
      dtype='object')

In [53]:
train_df["Age"] = cleaning_int_variables(train_df["Age"], "_", "", int)
train_df["Annual_Income"] = cleaning_int_variables(
    train_df["Annual_Income"], "_", "", float
)
train_df["Num_of_Loan"] = cleaning_int_variables(train_df["Num_of_Loan"], "_", "", int)
train_df["Changed_Credit_Limit"] = cleaning_int_variables(
    train_df["Changed_Credit_Limit"], "_", "0", float
)
train_df["Outstanding_Debt"] = cleaning_int_variables(
    train_df["Outstanding_Debt"], "_", "", float
)
train_df["Amount_invested_monthly"] = cleaning_int_variables(
    train_df["Amount_invested_monthly"], "_", "", float
)
train_df["Monthly_Balance"] = cleaning_int_variables(
    train_df["Monthly_Balance"], "_", "", float
)
train_df["Num_of_Delayed_Payment"] = cleaning_int_variables(
    train_df["Num_of_Delayed_Payment"], "_", "", float
)

In [54]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  int64
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  float64
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  int64
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   float64
 16  Changed_Credit_Limit      100000 non-null  float64
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  float64
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   float64
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           97132 non-null   float64
 27  Credit_Score              100000 non-null  object
dtypes: float64(10), int64(6), object(12)
memory usage: 21.4+ MB

In [55]:
numeric_df = train_df.select_dtypes(include="number")
numeric_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 16 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   Age                       100000 non-null  int64
 1   Annual_Income             100000 non-null  float64
 2   Monthly_Inhand_Salary     84998 non-null   float64
 3   Num_Bank_Accounts         100000 non-null  int64
 4   Num_Credit_Card           100000 non-null  int64
 5   Interest_Rate             100000 non-null  int64
 6   Num_of_Loan               100000 non-null  int64
 7   Delay_from_due_date       100000 non-null  int64
 8   Num_of_Delayed_Payment    92998 non-null   float64
 9   Changed_Credit_Limit      100000 non-null  float64
 10  Num_Credit_Inquiries      98035 non-null   float64
 11  Outstanding_Debt          100000 non-null  float64
 12  Credit_Utilization_Ratio  100000 non-null  float64
 13  Total_EMI_per_month       100000 non-null  float64
 14  Amount_invested_monthly   95521 non-null   float64
 15  Monthly_Balance           97132 non-null   float64
dtypes: float64(10), int64(6)
memory usage: 12.2 MB

In [56]:
numeric_df.describe()

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance
count,"100,000.00","100,000.00","84,998.00","100,000.00","100,000.00","100,000.00","100,000.00","100,000.00","92,998.00","100,000.00","98,035.00","100,000.00","100,000.00","100,000.00","95,521.00","97,132.00"
mean,110.65,"176,415.70","4,194.17",17.09,22.47,72.47,3.01,21.07,30.92,10.17,27.75,"1,426.22",32.29,"1,403.12",637.41,"-30,885,804,884,075,277,713,408.00"
std,686.24,"1,429,618.05","3,183.69",117.40,129.06,466.42,62.65,14.86,226.03,6.88,193.18,"1,155.13",5.12,"8,306.04","2,043.32","3,208,491,911,407,571,723,878,400.00"
min,-500.00,"7,005.93",303.65,-1.00,0.00,1.00,-100.00,-5.00,-3.00,-6.49,0.00,0.23,20.00,0.00,0.00,"-333,333,333,333,333,314,856,026,112.00"
25%,24.00,"19,457.50","1,625.57",3.00,4.00,8.00,1.00,10.00,9.00,4.97,3.00,566.07,28.05,30.31,74.53,269.99
50%,33.00,"37,578.61","3,093.75",6.00,5.00,13.00,3.00,18.00,14.00,9.25,6.00,"1,166.15",32.31,69.25,135.93,336.45
75%,42.00,"72,790.92","5,957.45",7.00,7.00,20.00,5.00,28.00,18.00,14.66,9.00,"1,945.96",36.50,161.22,265.73,469.64
max,"8,698.00","24,198,062.00","15,204.63","1,798.00","1,499.00","5,797.00","1,496.00",67.00,"4,397.00",36.97,"2,597.00","4,998.07",50.00,"82,331.00","10,000.00","1,602.04"

In [57]:
categorical_variables = [
    "Occupation",
    "Type_of_Loan",
    "Credit_Mix",
    "Payment_Behaviour",
    "Payment_of_Min_Amount",
]

In [58]:
train_df[train_df["Occupation"] == "_______"]

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
8,0x160e,CUS_0x21b1,January,Rick Rothackerj,28,004-07-5839,_______,"34,847.84","3,037.99",2,4,6,1,Credit-Builder Loan,3,4.00,5.42,2.00,Good,605.03,24.46,26 Years and 7 Months,No,18.82,104.29,Low_spent_Small_value_payments,470.69,Standard
16,0x161a,CUS_0x2dbc,January,Langep,34,486-85-3974,_______,"143,162.64","12,187.22",1,5,8,3,"Auto Loan, Auto Loan, and Not Specified",5,8.00,7.10,3.00,Good,"1,303.01",28.62,17 Years and 9 Months,No,246.99,168.41,!@9#%8,"1,043.32",Good
18,0x161c,CUS_0x2dbc,March,Langep,34,486-85-3974,_______,"143,162.64",NaN,1,5,8,3,"Auto Loan, Auto Loan, and Not Specified",8,7.00,11.10,NaN,Good,"1,303.01",26.52,17 Years and 11 Months,No,246.99,"10,000.00",High_spent_Small_value_payments,715.74,Good
20,0x161e,CUS_0x2dbc,May,Langep,34,486-85-3974,_______,"143,162.64","12,187.22",1,5,8,3,"Auto Loan, Auto Loan, and Not Specified",10,5.00,7.10,3.00,Good,"1,303.01",31.38,18 Years and 1 Months,No,246.99,430.95,Low_spent_Large_value_payments,810.78,Good
29,0x162b,CUS_0xb891,June,Jasond,55,#F%$D@*&8,_______,"30,689.89","2,612.49",2,5,4,1,Not Specified,5,6.00,-3.01,4.00,_,632.46,27.45,17 Years and 8 Months,No,16.42,84.95,High_spent_Small_value_payments,419.88,Standard
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99920,0x25f7a,CUS_0x2654,January,enj,37,647-67-8889,_______,"139,664.96","11,777.75",3,6,12,4,"Credit-Builder Loan, Credit-Builder Loan, Stud...",14,12.00,18.39,8.00,_,365.66,31.04,29 Years and 7 Months,Yes,423.73,282.78,High_spent_Large_value_payments,NaN,Standard
99935,0x25f8d,CUS_0xb11c,August,Yinka Adegokej,38,546-94-4789,_______,"15,319.65","1,460.64",6,7,15,4,"Home Equity Loan, Auto Loan, Auto Loan, and Au...",54,16.00,17.13,6.00,Bad,"1,453.61",34.56,11 Years and 4 Months,Yes,28.18,191.88,Low_spent_Small_value_payments,NaN,Poor
99937,0x25f93,CUS_0xad4f,February,Sabina Zawadzkig,-500,226-45-0652,_______,"22,620.79","1,722.07",7,3,9,0,NaN,25,NaN,5.31,2.00,Standard,642.46,31.84,NaN,No,0.00,105.08,Low_spent_Large_value_payments,NaN,Standard
99943,0x25f99,CUS_0xad4f,August,Sabina Zawadzkig,48,226-45-0652,_______,"22,620.79",NaN,6,2,9,0,NaN,27,15.00,5.31,2.00,_,642.46,34.03,29 Years and 10 Months,No,0.00,205.22,Low_spent_Small_value_payments,NaN,Poor
99989,0x25fdf,CUS_0x8600,June,Sarah McBridec,28,031-35-0942,_______,"20,002.88","1,929.91",10,8,29,5,"Personal Loan, Auto Loan, Mortgage Loan, Stude...",33,25.00,16.31,9.00,Bad,"3,571.70",33.36,6 Years and 1 Months,Yes,60.96,74.37,!@9#%8,NaN,Standard

In [59]:
train_df[train_df["Customer_ID"] == "CUS_0x9e67"]

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
93280,0x23892,CUS_0x9e67,January,Marias,24,366-87-4584,_______,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",11,9.00,10.74,NaN,_,"1,270.97",37.33,NaN,Yes,63.79,91.47,High_spent_Medium_value_payments,445.18,Standard
93281,0x23893,CUS_0x9e67,February,NaN,24,366-87-4584,Media_Manager,"44,393.86",NaN,6,3,12,2,"Student Loan, and Payday Loan",15,11.00,10.74,3.00,Standard,"1,270.97",38.29,20 Years and 4 Months,Yes,63.79,48.74,High_spent_Large_value_payments,477.91,Standard
93282,0x23894,CUS_0x9e67,March,Marias,24,366-87-4584,_______,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",15,11.00,10.74,3.00,_,"1,270.97",29.12,20 Years and 5 Months,Yes,63.79,73.10,High_spent_Medium_value_payments,463.55,Standard
93283,0x23895,CUS_0x9e67,April,Marias,24,366-87-4584,_______,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",15,13.00,0.00,3.00,_,"1,270.97",27.48,NaN,Yes,63.79,218.85,Low_spent_Small_value_payments,357.81,Standard
93284,0x23896,CUS_0x9e67,May,NaN,24,366-87-4584,_______,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",19,11.00,10.74,3.00,Standard,"1,270.97",25.37,20 Years and 7 Months,Yes,63.79,129.96,Low_spent_Large_value_payments,426.69,Poor
93285,0x23897,CUS_0x9e67,June,Marias,24,366-87-4584,Media_Manager,"44,393.86",NaN,6,3,12,2,"Student Loan, and Payday Loan",15,9.00,0.00,3.00,_,"1,270.97",39.86,20 Years and 8 Months,Yes,63.79,182.16,High_spent_Small_value_payments,364.50,Standard
93286,0x23898,CUS_0x9e67,July,Marias,24,366-87-4584,_______,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",19,11.00,10.74,3.00,Standard,"1,270.97",33.90,20 Years and 9 Months,Yes,63.79,430.17,Low_spent_Small_value_payments,146.48,Poor
93287,0x23899,CUS_0x9e67,August,Marias,25,366-87-4584,Media_Manager,"44,393.86","3,504.49",6,3,12,2,"Student Loan, and Payday Loan",15,11.00,12.74,"2,170.00",Standard,"1,270.97",30.15,20 Years and 10 Months,Yes,63.79,73.10,High_spent_Medium_value_payments,463.56,Poor

In [60]:
train_df[train_df["Occupation"] == "_______"].groupby("Month").size()

Month
April       928
August      880
February    900
January     827
July        823
June        948
March       877
May         879
dtype: int64

In [61]:
train_df[train_df["Occupation"] == "_______"].groupby("Customer_ID").size().sort_values(
    ascending=False
)

Customer_ID
CUS_0x9e67    5
CUS_0xb5e9    4
CUS_0xa146    4
CUS_0x1226    4
CUS_0x1f19    4
             ..
CUS_0x5704    1
CUS_0x56f6    1
CUS_0x56f     1
CUS_0x56e5    1
CUS_0xffd     1
Length: 5550, dtype: int64

In [62]:
train_df.groupby("Customer_ID")["Occupation"].nunique().sort_values(ascending=False)

Customer_ID
CUS_0x6da9    2
CUS_0x4aef    2
CUS_0x74fc    2
CUS_0x74f7    2
CUS_0x74e8    2
             ..
CUS_0x7968    1
CUS_0x7967    1
CUS_0x367d    1
CUS_0x7960    1
CUS_0x1000    1
Name: Occupation, Length: 12500, dtype: int64

In [63]:
valid_occupations = (
    train_df[train_df["Occupation"] != "_______"]
    .groupby("Customer_ID")["Occupation"]
    .first()
)
train_df["Occupation_filled"] = train_df["Customer_ID"].map(valid_occupations)
train_df["Occupation_filled"]

0        Scientist
1        Scientist
2        Scientist
3        Scientist
4        Scientist
           ...
99995     Mechanic
99996     Mechanic
99997     Mechanic
99998     Mechanic
99999     Mechanic
Name: Occupation_filled, Length: 100000, dtype: object

In [66]:
train_df.loc[train_df["Occupation"] == "_______", "Occupation"] = train_df[
    "Occupation_filled"
]
train_df["Occupation"].value_counts()

Occupation
Lawyer           7096
Engineer         6864
Architect        6824
Mechanic         6776
Scientist        6744
Accountant       6744
Developer        6720
Media_Manager    6720
Teacher          6672
Entrepreneur     6648
Doctor           6568
Journalist       6536
Manager          6432
Musician         6352
Writer           6304
Name: count, dtype: int64