# Context

The objective is to understand the data that we have!

# Libraries

In [2]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format
import os

/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Functions

In [3]:
def fast_feature_description(feature):
    
    print('---- NULL VALUES --')
    print(feature.isna().sum())
    print(feature.isna().mean())

    print('---- INFO --')
    print(feature.info())


    print('---- Common values --')
    print(feature.unique().shape)
    print(feature.unique())

# Loading data

In [4]:

train_df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "parisrohan/credit-score-classification",
  'train.csv'
)

test_df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "parisrohan/credit-score-classification",
  'test.csv'
)

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_53942/2619915194.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  train_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(
/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_53942/2619915194.py:7: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  test_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [5]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [6]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Customer_ID               50000 non-null  object
 2   Month                     50000 non-null  object
 3   Name                      44985 non-null  object
 4   Age                       50000 non-null  object
 5   SSN                       50000 non-null  object
 6   Occupation                50000 non-null  object
 7   Annual_Income             50000 non-null  object
 8   Monthly_Inhand_Salary     42502 non-null  float64
 9   Num_Bank_Accounts         50000 non-null  int64
 10  Num_Credit_Card           50000 non-null  int64
 11  Interest_Rate             50000 non-null  int64
 12  Num_of_Loan               50000 non-null  object
 13  Type_of_Loan              44296 non-null  object
 14  Delay_from_due_date       50000 non-null  int64
 15  Num_of_Delayed_Payment    46502 non-null  object
 16  Changed_Credit_Limit      50000 non-null  object
 17  Num_Credit_Inquiries      48965 non-null  float64
 18  Credit_Mix                50000 non-null  object
 19  Outstanding_Debt          50000 non-null  object
 20  Credit_Utilization_Ratio  50000 non-null  float64
 21  Credit_History_Age        45530 non-null  object
 22  Payment_of_Min_Amount     50000 non-null  object
 23  Total_EMI_per_month       50000 non-null  float64
 24  Amount_invested_monthly   47729 non-null  object
 25  Payment_Behaviour         50000 non-null  object
 26  Monthly_Balance           49438 non-null  object
dtypes: float64(4), int64(4), object(19)
memory usage: 10.3+ MB

# Exploring the dataset - identifiers

In [7]:
print(train_df.shape)
train_df.head()

(100000, 28)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,"1,824.84",3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,11.27,4.00,_,809.98,26.82,22 Years and 1 Months,No,49.57,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.00,Good,809.98,31.94,NaN,No,49.57,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,_,4.00,Good,809.98,28.61,22 Years and 3 Months,No,49.57,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4,6.27,4.00,Good,809.98,31.38,22 Years and 4 Months,No,49.57,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,"1,824.84",3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.00,Good,809.98,24.80,22 Years and 5 Months,No,49.57,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [8]:
train_df['Credit_Score'].value_counts(normalize=True)

Credit_Score
Standard   0.53
Poor       0.29
Good       0.18
Name: proportion, dtype: float64

In [9]:
train_df['Customer_ID'].unique().size

12500

In [10]:
print(train_df['Month'].unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']

In [11]:
train_df.groupby('Month').size()

Month
April       12500
August      12500
February    12500
January     12500
July        12500
June        12500
March       12500
May         12500
dtype: int64

In [12]:
train_df['SSN'].unique().size

12501

In [13]:
train_df['Name'].unique().size

10140

In [14]:
train_df.groupby('Customer_ID')['SSN'].nunique().sort_values(ascending=False).head(10)

Customer_ID
CUS_0x6da9    2
CUS_0x544     2
CUS_0x5430    2
CUS_0x542f    2
CUS_0x542c    2
CUS_0xa088    2
CUS_0xa08b    2
CUS_0x5413    2
CUS_0x540e    2
CUS_0xa09c    2
Name: SSN, dtype: int64

In [15]:
train_df[train_df['Customer_ID'] == 'CUS_0x6da9']

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
77328,0x1db1a,CUS_0x6da9,January,Davidw,32,353-08-1853,_______,85426.68,"7,024.89",3,6,5,0,NaN,11,9,1.91,3.00,Good,1187.02,28.89,29 Years and 11 Months,No,0.00,70.71242566502217,!@9#%8,871.7765743349779,Standard
77329,0x1db1b,CUS_0x6da9,February,Davidw,32,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0,NaN,7,9,1.91,3.00,Good,1187.02,32.40,30 Years and 0 Months,No,0.00,326.3287023669127,Low_spent_Medium_value_payments,656.1602976330872,Standard
77330,0x1db1c,CUS_0x6da9,March,Davidw,32_,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,NaN,1.91,3.00,Good,1187.02,41.06,30 Years and 1 Months,No,0.00,__10000__,Low_spent_Large_value_payments,329.09595320745325,Standard
77331,0x1db1d,CUS_0x6da9,April,Davidw,33,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9,1.91,3.00,_,1187.02,34.45,30 Years and 2 Months,No,0.00,__10000__,Low_spent_Medium_value_payments,388.3133568992598,Standard
77332,0x1db1e,CUS_0x6da9,May,Davidw,33,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9,5.91,3.00,Good,1187.02,38.71,30 Years and 3 Months,No,0.00,455.40288905313264,High_spent_Small_value_payments,507.0861109468674,Standard
77333,0x1db1f,CUS_0x6da9,June,Davidw,33,353-08-1853,_______,85426.68,"7,024.89",3,6,5,0,NaN,11,9,-1.09,3.00,Good,1187.02,26.03,30 Years and 4 Months,No,0.00,448.3418078088855,Low_spent_Small_value_payments,544.1471921911145,Standard
77334,0x1db20,CUS_0x6da9,July,Davidw,33,353-08-1853,Manager,85426.68,"7,024.89",3,6,5,0,NaN,11,9_,-1.09,3.00,Good,1187.02,32.38,30 Years and 5 Months,No,0.00,454.88672005971495,Low_spent_Medium_value_payments,527.602279940285,Standard
77335,0x1db21,CUS_0x6da9,August,Davidw,33,#F%$D@*&8,Manager,85426.68,"7,024.89",3,6,5,0_,NaN,11,9,1.91,3.00,_,1187.02,27.74,30 Years and 6 Months,NM,0.00,856.9792955447119,Low_spent_Small_value_payments,135.50970445528807,Standard

In [16]:
a = train_df[train_df['Customer_ID'] == 'CUS_0x6da9']['Monthly_Inhand_Salary'].sum() 
b = 85426.68/7024.89
b

12.160571909311034

In [17]:
train_df[train_df['SSN'] == '#F%$D@*&8'].shape

(5572, 28)

In [18]:
train_df.duplicated().sum()

np.int64(0)

In [19]:
# essential identifiers:

ids = ['Customer_ID', 'num_month']

## Overview

- 100,000 rows
- 12,500 unique clients
- 8 months (JAN - AUG)
- Panel data structure
- There are null names
- We have corrputed SSN as '#F%$D@*&8'
- No duplicated rows

## Tasks:

- Convert the months into numbers to split the data temporally
- Ignore identifiers for now that does not provide important informationl ike name ssn,

In [20]:
month_mapping = {
    'January' : 202201,
    'February' : 202202,
    'March' : 202203,
    'April' : 202204,
    'May' : 202205,
    'June' : 202206,
    'July' : 202207,
    'August' : 202208,

}

train_df['num_month'] = train_df['Month'].map(month_mapping)

train_df['num_month'].value_counts()

num_month
202201    12500
202202    12500
202203    12500
202204    12500
202205    12500
202206    12500
202207    12500
202208    12500
Name: count, dtype: int64

# Target variable

In [21]:
target = 'Credit_Score'

counts = train_df[target].value_counts()
percentages = train_df[target].value_counts(normalize = True) * 100

summary = pd.DataFrame({
    'counts': counts,
    '%': percentages
})
summary

              counts     %
Credit_Score
Standard       53174 53.17
Poor           28998 29.00
Good           17828 17.83

In [22]:
pd.crosstab(
    train_df['num_month'],
    train_df[target],
    normalize='index'
)

Credit_Score  Good  Poor  Standard
num_month
202201        0.16  0.29      0.56
202202        0.16  0.28      0.56
202203        0.16  0.28      0.56
202204        0.19  0.29      0.52
202205        0.18  0.30      0.52
202206        0.19  0.30      0.51
202207        0.19  0.29      0.52
202208        0.19  0.29      0.52

# Numeric variables

In [23]:
numeric_variables = ['Age', 'Annual_Income','Monthly_Inhand_Salary','Num_Bank_Accounts','Interest_Rate','Num_of_Loan','Delay_from_due_date','Changed_Credit_Limit',
                     'Num_Credit_Inquiries','Outstanding_Debt', 'Credit_Utilization_Ratio','Credit_History_Age','Payment_of_Min_Amount', 'Total_EMI_per_month',
                     'Amount_invested_monthly','Monthly_Balance', 'Num_of_Delayed_Payment']

len(numeric_variables)

17

In [24]:
train_df[numeric_variables]

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Interest_Rate,Num_of_Loan,Delay_from_due_date,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Num_of_Delayed_Payment
0,23,19114.12,"1,824.84",3,3,4,3,11.27,4.00,809.98,26.82,22 Years and 1 Months,No,49.57,80.41529543900253,312.49408867943663,7
1,23,19114.12,NaN,3,3,4,-1,11.27,4.00,809.98,31.94,NaN,No,49.57,118.28022162236736,284.62916249607184,NaN
2,-500,19114.12,NaN,3,3,4,3,_,4.00,809.98,28.61,22 Years and 3 Months,No,49.57,81.699521264648,331.2098628537912,7
3,23,19114.12,NaN,3,3,4,5,6.27,4.00,809.98,31.38,22 Years and 4 Months,No,49.57,199.4580743910713,223.45130972736786,4
4,23,19114.12,"1,824.84",3,3,4,6,11.27,4.00,809.98,24.80,22 Years and 5 Months,No,49.57,41.420153086217326,341.48923103222177,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,39628.99,"3,359.42",4,7,2,23,11.5,3.00,502.38,34.66,31 Years and 6 Months,No,35.10,60.97133255718485,479.87,7
99996,25,39628.99,"3,359.42",4,7,2,18,11.5,3.00,502.38,40.57,31 Years and 7 Months,No,35.10,54.18595028760385,496.65,7
99997,25,39628.99,"3,359.42",4,5729,2,27,11.5,3.00,502.38,41.26,31 Years and 8 Months,No,35.10,24.02847744864441,516.81,6
99998,25,39628.99,"3,359.42",4,7,2,20,11.5,3.00,502.38,33.64,31 Years and 9 Months,No,35.10,251.67258219721603,319.16,NaN
99999,25,39628.99_,"3,359.42",4,7,2,18,11.5,3.00,502.38,34.19,31 Years and 10 Months,No,35.10,167.1638651610451,393.67,6

## Age

In [25]:
print(train_df['Age'].isna().sum())
print(train_df['Age'].isna().mean())
train_df['Age'].info()

0
0.0
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Age
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB

In [26]:
print(train_df['Age'].unique().shape)

train_df['Age'].unique()

(1788,)

array(['23', '-500', '28_', ..., '4808_', '2263', '1342'], dtype=object)

In [27]:
train_df['Age'] = train_df['Age'].str.replace('_', '')
train_df['Age'] = train_df['Age'].astype(int)

In [28]:
train_df['Age'].describe()

count   100,000.00
mean        110.65
std         686.24
min        -500.00
25%          24.00
50%          33.00
75%          42.00
max       8,698.00
Name: Age, dtype: float64

## Annual Income

In [29]:
fast_feature_description(train_df['Annual_Income'])

---- NULL VALUES --
0
0.0
---- INFO --
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Annual_Income
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB
None
---- Common values --
(18940,)
['19114.12' '34847.84' '34847.84_' ... '20002.88' '39628.99' '39628.99_']

In [30]:
print(train_df['Annual_Income'].unique().shape)

train_df['Annual_Income'].unique()

(18940,)

array(['19114.12', '34847.84', '34847.84_', ..., '20002.88', '39628.99',
       '39628.99_'], dtype=object)

In [31]:
train_df['Annual_Income'] = train_df['Annual_Income'].str.replace('_', '')

In [32]:
train_df['Annual_Income'] = train_df['Annual_Income'].astype(float)

In [33]:
train_df['Annual_Income'].describe()

count      100,000.00
mean       176,415.70
std      1,429,618.05
min          7,005.93
25%         19,457.50
50%         37,578.61
75%         72,790.92
max     24,198,062.00
Name: Annual_Income, dtype: float64

## Monthly_Inhand_Salary

In [34]:
fast_feature_description(train_df['Monthly_Inhand_Salary'])

---- NULL VALUES --
15002
0.15002
---- INFO --
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Monthly_Inhand_Salary
Non-Null Count  Dtype
--------------  -----
84998 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
---- Common values --
(13236,)
[1824.84333333           nan 3037.98666667 ... 3097.00833333 1929.90666667
 3359.41583333]

In [35]:
train_df['Monthly_Inhand_Salary'].describe()

count   84,998.00
mean     4,194.17
std      3,183.69
min        303.65
25%      1,625.57
50%      3,093.75
75%      5,957.45
max     15,204.63
Name: Monthly_Inhand_Salary, dtype: float64

In [36]:
train_df['avg_salary'] = train_df['Annual_Income'] / train_df['Monthly_Inhand_Salary']
train_df['avg_salary'].describe()

count   84,998.00
mean        67.24
std        846.10
min          8.09
25%         11.55
50%         12.03
75%         12.55
max     54,110.52
Name: avg_salary, dtype: float64

## Num bank accounts

In [41]:
fast_feature_description(train_df['Num_Bank_Accounts'])

---- NULL VALUES --
0
0.0
---- INFO --
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Num_Bank_Accounts
Non-Null Count   Dtype
--------------   -----
100000 non-null  int64
dtypes: int64(1)
memory usage: 781.4 KB
None
---- Common values --
(943,)
[   3    2    1    7    4    0    8    5    6    9   10 1414 1231   67
  572 1488   91  528 1647 1696 1338  649  889 1668  685  857  975 1496
 1534 1620   37 1388 1429 1332 1588  120 1777 1096  803  494  744 1139
  831 1613  741  121  665 1748 1644  823 1356 1651   87  711  450  210
 1671 1722  648  672 1662 1495  510  666  429 1131 1434  980 1026  526
  718 1300 1312 1315  501 1566  480 1042  322  628 1016  333 1265  791
  427  563  905 1190 1036 1611   38  619  555 1769  280  752 1201  812
 1487  222  212 1019 1222  610 1714 1308  525 1158 1115 1616  754 1601
  797 1577  521  703  933  959  809 1089 1656 1113 1715  964 1533 1789
  871  434 1295  565 1724  603  677  541  698 1101  464 1539 1462 1011
 1257 1727   45  244 1266  897  535  484  331  675  826  946 1675  105
 1327  845  549  473  710  527  908   68 1628  371  445 1168  868  687
  455 1003   26 1526  618  598  351 1342 1783  683 1557 1335  416 1747
  137 1475  373  338  942  170  973 1605 1478  386 1448 1033 1225  596
 1731 1214 1481 1105  580  347  108  148 1001 1467 1114 1000  632  246
 1032 1394  689  482 1303  720  574  588 1358  650  708  179  844 1140
  335   60  732 1494 1436  820   28 1576  818  794  731  534  556  691
 1197 1155 1255 1763  769 1124  819  318 1418  882   61  264  194 1798
  611  840  505 1110  719 1065  195  584  550 1014 1022  903  976   31
  417 1423 1148  616  786 1424   55 1061 1293  342   43 1540  488 1122
 1274 1075  722 1268   41  814 1564 1390 1141  497  224 1135  441  374
   74  314 1408  475 1015  681 1236   59 1425 1637 1240  299 1657 1123
 1091 1264 1561 1632 1562  305 1318 1217 1699 1070  864 1391  112  860
  595  229 1624 1051  821 1794 1565  397 1368 1353  508 1725 1413 1239
  847 1317  570   -1  302  456  198  122  832  167 1547 1666 1241  275
  566 1779  201  334 1169  834 1174 1040  530 1676 1468 1093  706  489
 1592  688  830 1784 1543 1600 1178  228  483 1501  950  548  870 1211
  604  804  129  540 1702 1636 1680 1443 1252  499  180  702  885 1652
  795  938  833 1654 1793  303 1621 1516 1138   32  160 1491   83  423
  928  339  931  243 1756  583 1695  274  955  430 1247  490  726  987
   42 1626 1470 1739  887  211  385 1221  753  324  406 1677 1567  785
  182 1079  184 1771 1048 1069  561  589 1634   70 1371  647 1153  239
  801 1279 1287  425 1589  929 1511 1765 1047 1005 1337  981 1766  805
 1574 1638  186   99  288 1650  974  996 1595 1594  865  203 1440  448
  285   94  875  916 1733  240  330   79   82  135 1043  142 1235 1569
 1741 1461  560 1551  409  418 1017  892  354  124  935  313 1363  232
 1200 1184 1432 1479 1407 1080 1719 1024  970  761  158  312 1060  684
  696 1520 1352 1502  936  485  350 1560 1166 1013   34 1691  715 1570
 1751 1503 1194 1558  411  298  260  308  796 1442  912 1256  746  435
  620 1774 1181 1323  837  307 1430   53 1447  259  921  328 1034  353
  822  654  829  609  166  136  172 1306 1028  808  270 1072  514  156
 1331 1630  462 1310 1210  265   50 1355  394 1393  226  991  368 1018
 1037  627 1744  523  894  944 1730 1076 1094 1617  449  678 1164   30
  817 1568  607  709 1230  606 1480   29 1522 1670   49  626 1641 1712
 1370 1782  119 1137 1277   35  947  851 1041 1583 1536  575  196  143
   33  383   57  621  230  162  352 1504 1250   39  511 1364  918 1665
  734 1320  316  771  705 1435  304  116 1553  424  493 1530 1195 1604
  624 1599  782 1606 1622 1285  657 1275 1291 1402  420  932  468  442
 1145   93 1218  283  292  927 1711 1422  364 1398  594  789 1350  676
  216 1012 1426  717 1095 1786  850  777  375  356  701 1325  290 1775
  467 1365 1549  848 1453   84 1458  888  770 1591  582   40 1261 1764
 1067  145  471  476 1128  967  622  641  539  858  295 1395 1517 1297
 1126  926  157 1377  993  125  340  271 1669  272  979  707  564  997
  447 1578 1465  415  714 1276   18 1316  587  245  446  978 1002 1631
  341 1307  524 1267  103  242 1378 1328 1294 1309  724  197  999  547
 1100 1456   77 1506 1472  460   11 1420  218 1253  392  670 1321  100
 1205  443   92  811  774  159 1770  972 1157 1102  217  358 1473  440
  140 1361  481  512 1117  300 1263 1581  901 1298  310  637  758 1734
 1288  326 1678 1444 1344 1379  828  982  104  317 1529 1627  115  645
 1404  940 1305 1049 1645 1466  175 1165 1419 1031  581 1580  854  725
 1655 1134  569 1387 1381 1760  360 1735 1146 1411  969 1281  591  327
  466  667  147  109  784 1396 1349  839 1284  802   97  281 1382 1039
 1483  376 1249 1207 1213 1219 1345 1523  949 1063  983  886 1151  992
 1107 1314  151   69 1489  695  738  444 1525  825  506  518 1077 1354
  713  690  861 1389  968  421  907  205  856   72  651  161  867  971
 1078   64 1701  546 1216   27 1709  193 1528  957  577  346 1416  396
 1182  652 1083 1778  680 1754 1544 1703  636  472  453  463   75  756
  296  891  813  474  697]

In [42]:
train_df['Num_Bank_Accounts'].describe()

count   100,000.00
mean         17.09
std         117.40
min          -1.00
25%           3.00
50%           6.00
75%           7.00
max       1,798.00
Name: Num_Bank_Accounts, dtype: float64

## Overview

1. Age
- Convert age from strings to int and clean the values with '_'
- Clean outliers and non sense values (thing if we should take them as null values, erros, the best action here is to take the corresponding age of the client in other months)
2. Annual Income:
- Convert the colum from string to float and clean the values with '_'
- It seems accurate, in cleaning check if the monthly salary corresponds to the annual income
3. Monthly Inhand Salary:
- Already float, high null percentage (15%)
- Does not correspond always to the annual income, check for correlation
4. Num bank accounts:
- Already float, with meaningless values to fix (outliers too)

# Categorical Variables

In [38]:
categorical_variables = ['Occupation','Type_of_Loan','Credit_Mix','Payment_Behaviour']

In [39]:
train_df[categorical_variables]

,Occupation,Type_of_Loan,Credit_Mix,Payment_Behaviour
0,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",_,High_spent_Small_value_payments
1,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Large_value_payments
2,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Medium_value_payments
3,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Small_value_payments
4,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,High_spent_Medium_value_payments
...,...,...,...,...
99995,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Large_value_payments
99996,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Medium_value_payments
99997,Mechanic,"Auto Loan, and Student Loan",Good,High_spent_Large_value_payments
99998,Mechanic,"Auto Loan, and Student Loan",Good,Low_spent_Large_value_payments
99999,Mechanic,"Auto Loan, and Student Loan",Good,!@9#%8

In [40]:
remaining_cols = set(train_df.columns) - set(numeric_variables) - set(categorical_variables) - set(ids)
remaining_cols

{'Credit_Score', 'ID', 'Month', 'Name', 'Num_Credit_Card', 'SSN', 'avg_salary'}