# Context

The objective is to understand the data that we have!

# Libraries

In [75]:
import pandas as pd
pd.set_option('display.max_columns', None)
import os

# Loading data

In [86]:
train_df = pd.read_csv("../data/train.csv")
test_df = pd.read_csv("../data/test.csv")

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_30276/3018219347.py:1: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  train_df = pd.read_csv("../data/train.csv")

In [89]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [20]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Customer_ID               50000 non-null  object
 2   Month                     50000 non-null  object
 3   Name                      44985 non-null  object
 4   Age                       50000 non-null  object
 5   SSN                       50000 non-null  object
 6   Occupation                50000 non-null  object
 7   Annual_Income             50000 non-null  object
 8   Monthly_Inhand_Salary     42502 non-null  float64
 9   Num_Bank_Accounts         50000 non-null  int64
 10  Num_Credit_Card           50000 non-null  int64
 11  Interest_Rate             50000 non-null  int64
 12  Num_of_Loan               50000 non-null  object
 13  Type_of_Loan              44296 non-null  object
 14  Delay_from_due_date       50000 non-null  int64
 15  Num_of_Delayed_Payment    46502 non-null  object
 16  Changed_Credit_Limit      50000 non-null  object
 17  Num_Credit_Inquiries      48965 non-null  float64
 18  Credit_Mix                50000 non-null  object
 19  Outstanding_Debt          50000 non-null  object
 20  Credit_Utilization_Ratio  50000 non-null  float64
 21  Credit_History_Age        45530 non-null  object
 22  Payment_of_Min_Amount     50000 non-null  object
 23  Total_EMI_per_month       50000 non-null  float64
 24  Amount_invested_monthly   47729 non-null  object
 25  Payment_Behaviour         50000 non-null  object
 26  Monthly_Balance           49438 non-null  object
dtypes: float64(4), int64(4), object(19)
memory usage: 10.3+ MB

# Exploring the dataset - identifiers

In [26]:
print(train_df.shape)
train_df.head()

(100000, 28)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,...,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,...,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,...,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [100]:
train_df['Credit_Score'].value_counts(normalize=True)

Credit_Score
Standard    0.53174
Poor        0.28998
Good        0.17828
Name: proportion, dtype: float64

In [41]:
train_df['Customer_ID'].unique().size

12500

In [34]:
print(train_df['Month'].unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']

In [45]:
train_df.groupby('Month').size()

Month
April       12500
August      12500
February    12500
January     12500
July        12500
June        12500
March       12500
May         12500
dtype: int64

In [65]:
train_df['SSN'].unique().size

12501

In [53]:
train_df['Name'].unique().size

10140

In [71]:
train_df.groupby('Customer_ID')['SSN'].nunique().sort_values(ascending=False).head(10)

Customer_ID
CUS_0x6da9    2
CUS_0x544     2
CUS_0x5430    2
CUS_0x542f    2
CUS_0x542c    2
CUS_0xa088    2
CUS_0xa08b    2
CUS_0x5413    2
CUS_0x540e    2
CUS_0xa09c    2
Name: SSN, dtype: int64

In [77]:
train_df[train_df['Customer_ID'] == 'CUS_0x6da9']

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
77328,0x1db1a,CUS_0x6da9,January,Davidw,32,353-08-1853,_______,85426.68,7024.89,3,6,5,0,NaN,11,9,1.91,3.0,Good,1187.02,28.886540,29 Years and 11 Months,No,0.0,70.71242566502217,!@9#%8,871.7765743349779,Standard
77329,0x1db1b,CUS_0x6da9,February,Davidw,32,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0,NaN,7,9,1.91,3.0,Good,1187.02,32.402340,30 Years and 0 Months,No,0.0,326.3287023669127,Low_spent_Medium_value_payments,656.1602976330872,Standard
77330,0x1db1c,CUS_0x6da9,March,Davidw,32_,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,NaN,1.91,3.0,Good,1187.02,41.055041,30 Years and 1 Months,No,0.0,__10000__,Low_spent_Large_value_payments,329.09595320745325,Standard
77331,0x1db1d,CUS_0x6da9,April,Davidw,33,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9,1.91,3.0,_,1187.02,34.448058,30 Years and 2 Months,No,0.0,__10000__,Low_spent_Medium_value_payments,388.3133568992598,Standard
77332,0x1db1e,CUS_0x6da9,May,Davidw,33,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9,5.91,3.0,Good,1187.02,38.711419,30 Years and 3 Months,No,0.0,455.40288905313264,High_spent_Small_value_payments,507.0861109468674,Standard
77333,0x1db1f,CUS_0x6da9,June,Davidw,33,353-08-1853,_______,85426.68,7024.89,3,6,5,0,NaN,11,9,-1.09,3.0,Good,1187.02,26.025466,30 Years and 4 Months,No,0.0,448.3418078088855,Low_spent_Small_value_payments,544.1471921911145,Standard
77334,0x1db20,CUS_0x6da9,July,Davidw,33,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9_,-1.09,3.0,Good,1187.02,32.375452,30 Years and 5 Months,No,0.0,454.88672005971495,Low_spent_Medium_value_payments,527.602279940285,Standard
77335,0x1db21,CUS_0x6da9,August,Davidw,33,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0_,NaN,11,9,1.91,3.0,_,1187.02,27.735306,30 Years and 6 Months,NM,0.0,856.9792955447119,Low_spent_Small_value_payments,135.50970445528807,Standard

In [82]:
a = train_df[train_df['Customer_ID'] == 'CUS_0x6da9']['Monthly_Inhand_Salary'].sum() 
b = 85426.68/7024.89
b

12.160571909311034

In [98]:
train_df[train_df['SSN'] == '#F%$D@*&8'].shape

(5572, 28)

In [99]:
train_df.duplicated().sum()

np.int64(0)

## Overview

- 100,000 rows
- 12,500 unique clients
- 8 months (JAN - AUG)
- Panel data structure
- There are null names
- We have corrputed SSN as '#F%$D@*&8'
- No duplicated rows