# Context

The objective is to understand the data that we have!

# Libraries

In [112]:
import kagglehub
from kagglehub import KaggleDatasetAdapter
import pandas as pd
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format
import os

# Functions

In [118]:
def fast_feature_description(feature):
    
    print('---- NULL VALUES --')
    print(feature.isna().sum())
    print(feature.isna().mean())

    print('---- INFO --')
    print(feature.info())


    print('---- Common values --')
    print(feature.unique().shape)
    print(feature.unique())

# Loading data

In [2]:

train_df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "parisrohan/credit-score-classification",
  'train.csv'
)

test_df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "parisrohan/credit-score-classification",
  'test.csv'
)

/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_48194/2619915194.py:1: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  train_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

/Users/luisfernandocorcueraleon/Desktop/code/Credit-Score-Classification/.venv/lib/python3.9/site-packages/kagglehub/pandas_datasets.py:91: DtypeWarning: Columns (26) have mixed types. Specify dtype option on import or set low_memory=False.
  result = read_function(
/var/folders/1f/54wv342x795c_zyzqlgyjjkw0000gn/T/ipykernel_48194/2619915194.py:7: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  test_df = kagglehub.load_dataset(

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).

In [3]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 28 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   ID                        100000 non-null  object
 1   Customer_ID               100000 non-null  object
 2   Month                     100000 non-null  object
 3   Name                      90015 non-null   object
 4   Age                       100000 non-null  object
 5   SSN                       100000 non-null  object
 6   Occupation                100000 non-null  object
 7   Annual_Income             100000 non-null  object
 8   Monthly_Inhand_Salary     84998 non-null   float64
 9   Num_Bank_Accounts         100000 non-null  int64
 10  Num_Credit_Card           100000 non-null  int64
 11  Interest_Rate             100000 non-null  int64
 12  Num_of_Loan               100000 non-null  object
 13  Type_of_Loan              88592 non-null   object
 14  Delay_from_due_date       100000 non-null  int64
 15  Num_of_Delayed_Payment    92998 non-null   object
 16  Changed_Credit_Limit      100000 non-null  object
 17  Num_Credit_Inquiries      98035 non-null   float64
 18  Credit_Mix                100000 non-null  object
 19  Outstanding_Debt          100000 non-null  object
 20  Credit_Utilization_Ratio  100000 non-null  float64
 21  Credit_History_Age        90970 non-null   object
 22  Payment_of_Min_Amount     100000 non-null  object
 23  Total_EMI_per_month       100000 non-null  float64
 24  Amount_invested_monthly   95521 non-null   object
 25  Payment_Behaviour         100000 non-null  object
 26  Monthly_Balance           98800 non-null   object
 27  Credit_Score              100000 non-null  object
dtypes: float64(4), int64(4), object(20)
memory usage: 21.4+ MB

In [4]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   ID                        50000 non-null  object
 1   Customer_ID               50000 non-null  object
 2   Month                     50000 non-null  object
 3   Name                      44985 non-null  object
 4   Age                       50000 non-null  object
 5   SSN                       50000 non-null  object
 6   Occupation                50000 non-null  object
 7   Annual_Income             50000 non-null  object
 8   Monthly_Inhand_Salary     42502 non-null  float64
 9   Num_Bank_Accounts         50000 non-null  int64
 10  Num_Credit_Card           50000 non-null  int64
 11  Interest_Rate             50000 non-null  int64
 12  Num_of_Loan               50000 non-null  object
 13  Type_of_Loan              44296 non-null  object
 14  Delay_from_due_date       50000 non-null  int64
 15  Num_of_Delayed_Payment    46502 non-null  object
 16  Changed_Credit_Limit      50000 non-null  object
 17  Num_Credit_Inquiries      48965 non-null  float64
 18  Credit_Mix                50000 non-null  object
 19  Outstanding_Debt          50000 non-null  object
 20  Credit_Utilization_Ratio  50000 non-null  float64
 21  Credit_History_Age        45530 non-null  object
 22  Payment_of_Min_Amount     50000 non-null  object
 23  Total_EMI_per_month       50000 non-null  float64
 24  Amount_invested_monthly   47729 non-null  object
 25  Payment_Behaviour         50000 non-null  object
 26  Monthly_Balance           49438 non-null  object
dtypes: float64(4), int64(4), object(19)
memory usage: 10.3+ MB

# Exploring the dataset - identifiers

In [5]:
print(train_df.shape)
train_df.head()

(100000, 28)

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
0,0x1602,CUS_0xd40,January,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,11.27,4.0,_,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,High_spent_Small_value_payments,312.49408867943663,Good
1,0x1603,CUS_0xd40,February,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",-1,NaN,11.27,4.0,Good,809.98,31.944960,NaN,No,49.574949,118.28022162236736,Low_spent_Large_value_payments,284.62916249607184,Good
2,0x1604,CUS_0xd40,March,Aaron Maashoh,-500,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",3,7,_,4.0,Good,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,Low_spent_Medium_value_payments,331.2098628537912,Good
3,0x1605,CUS_0xd40,April,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,NaN,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",5,4,6.27,4.0,Good,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,Low_spent_Small_value_payments,223.45130972736786,Good
4,0x1606,CUS_0xd40,May,Aaron Maashoh,23,821-00-0265,Scientist,19114.12,1824.843333,3,4,3,4,"Auto Loan, Credit-Builder Loan, Personal Loan,...",6,NaN,11.27,4.0,Good,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,High_spent_Medium_value_payments,341.48923103222177,Good

In [6]:
train_df['Credit_Score'].value_counts(normalize=True)

Credit_Score
Standard    0.53174
Poor        0.28998
Good        0.17828
Name: proportion, dtype: float64

In [7]:
train_df['Customer_ID'].unique().size

12500

In [8]:
print(train_df['Month'].unique())

['January' 'February' 'March' 'April' 'May' 'June' 'July' 'August']

In [9]:
train_df.groupby('Month').size()

Month
April       12500
August      12500
February    12500
January     12500
July        12500
June        12500
March       12500
May         12500
dtype: int64

In [10]:
train_df['SSN'].unique().size

12501

In [11]:
train_df['Name'].unique().size

10140

In [12]:
train_df.groupby('Customer_ID')['SSN'].nunique().sort_values(ascending=False).head(10)

Customer_ID
CUS_0x6da9    2
CUS_0x544     2
CUS_0x5430    2
CUS_0x542f    2
CUS_0x542c    2
CUS_0xa088    2
CUS_0xa08b    2
CUS_0x5413    2
CUS_0x540e    2
CUS_0xa09c    2
Name: SSN, dtype: int64

In [13]:
train_df[train_df['Customer_ID'] == 'CUS_0x6da9']

,ID,Customer_ID,Month,Name,Age,SSN,Occupation,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Num_Credit_Card,Interest_Rate,Num_of_Loan,Type_of_Loan,Delay_from_due_date,Num_of_Delayed_Payment,Changed_Credit_Limit,Num_Credit_Inquiries,Credit_Mix,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Payment_Behaviour,Monthly_Balance,Credit_Score
77328,0x1db1a,CUS_0x6da9,January,Davidw,32,353-08-1853,_______,85426.68,7024.89,3,6,5,0,NaN,11,9,1.91,3.0,Good,1187.02,28.886540,29 Years and 11 Months,No,0.0,70.71242566502217,!@9#%8,871.7765743349779,Standard
77329,0x1db1b,CUS_0x6da9,February,Davidw,32,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0,NaN,7,9,1.91,3.0,Good,1187.02,32.402340,30 Years and 0 Months,No,0.0,326.3287023669127,Low_spent_Medium_value_payments,656.1602976330872,Standard
77330,0x1db1c,CUS_0x6da9,March,Davidw,32_,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,NaN,1.91,3.0,Good,1187.02,41.055041,30 Years and 1 Months,No,0.0,__10000__,Low_spent_Large_value_payments,329.09595320745325,Standard
77331,0x1db1d,CUS_0x6da9,April,Davidw,33,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9,1.91,3.0,_,1187.02,34.448058,30 Years and 2 Months,No,0.0,__10000__,Low_spent_Medium_value_payments,388.3133568992598,Standard
77332,0x1db1e,CUS_0x6da9,May,Davidw,33,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9,5.91,3.0,Good,1187.02,38.711419,30 Years and 3 Months,No,0.0,455.40288905313264,High_spent_Small_value_payments,507.0861109468674,Standard
77333,0x1db1f,CUS_0x6da9,June,Davidw,33,353-08-1853,_______,85426.68,7024.89,3,6,5,0,NaN,11,9,-1.09,3.0,Good,1187.02,26.025466,30 Years and 4 Months,No,0.0,448.3418078088855,Low_spent_Small_value_payments,544.1471921911145,Standard
77334,0x1db20,CUS_0x6da9,July,Davidw,33,353-08-1853,Manager,85426.68,7024.89,3,6,5,0,NaN,11,9_,-1.09,3.0,Good,1187.02,32.375452,30 Years and 5 Months,No,0.0,454.88672005971495,Low_spent_Medium_value_payments,527.602279940285,Standard
77335,0x1db21,CUS_0x6da9,August,Davidw,33,#F%$D@*&8,Manager,85426.68,7024.89,3,6,5,0_,NaN,11,9,1.91,3.0,_,1187.02,27.735306,30 Years and 6 Months,NM,0.0,856.9792955447119,Low_spent_Small_value_payments,135.50970445528807,Standard

In [14]:
a = train_df[train_df['Customer_ID'] == 'CUS_0x6da9']['Monthly_Inhand_Salary'].sum() 
b = 85426.68/7024.89
b

12.160571909311034

In [15]:
train_df[train_df['SSN'] == '#F%$D@*&8'].shape

(5572, 28)

In [16]:
train_df.duplicated().sum()

np.int64(0)

In [65]:
# essential identifiers:

ids = ['Customer_ID', 'num_month']

## Overview

- 100,000 rows
- 12,500 unique clients
- 8 months (JAN - AUG)
- Panel data structure
- There are null names
- We have corrputed SSN as '#F%$D@*&8'
- No duplicated rows

## Tasks:

- Convert the months into numbers to split the data temporally
- Ignore identifiers for now that does not provide important informationl ike name ssn,

In [56]:
month_mapping = {
    'January' : 202201,
    'February' : 202202,
    'March' : 202203,
    'April' : 202204,
    'May' : 202205,
    'June' : 202206,
    'July' : 202207,
    'August' : 202208,

}

train_df['num_month'] = train_df['Month'].map(month_mapping)

train_df['num_month'].value_counts()

num_month
202201    12500
202202    12500
202203    12500
202204    12500
202205    12500
202206    12500
202207    12500
202208    12500
Name: count, dtype: int64

# Target variable

In [24]:
target = 'Credit_Score'

counts = train_df[target].value_counts()
percentages = train_df[target].value_counts(normalize = True) * 100

summary = pd.DataFrame({
    'counts': counts,
    '%': percentages
})
summary

              counts       %
Credit_Score
Standard       53174  53.174
Poor           28998  28.998
Good           17828  17.828

In [57]:
pd.crosstab(
    train_df['num_month'],
    train_df[target],
    normalize='index'
)

Credit_Score     Good     Poor  Standard
num_month
202201        0.15800  0.28656   0.55544
202202        0.16128  0.28312   0.55560
202203        0.15872  0.28408   0.55720
202204        0.18856  0.29360   0.51784
202205        0.18480  0.29696   0.51824
202206        0.18896  0.29824   0.51280
202207        0.19288  0.28912   0.51800
202208        0.19304  0.28816   0.51880

# Numeric variables

In [59]:
numeric_variables = ['Age', 'Annual_Income','Monthly_Inhand_Salary','Num_Bank_Accounts','Interest_Rate','Num_of_Loan','Delay_from_due_date','Changed_Credit_Limit',
                     'Num_Credit_Inquiries','Outstanding_Debt', 'Credit_Utilization_Ratio','Credit_History_Age','Payment_of_Min_Amount', 'Total_EMI_per_month',
                     'Amount_invested_monthly','Monthly_Balance', 'Num_of_Delayed_Payment']

len(numeric_variables)

17

In [60]:
train_df[numeric_variables]

,Age,Annual_Income,Monthly_Inhand_Salary,Num_Bank_Accounts,Interest_Rate,Num_of_Loan,Delay_from_due_date,Changed_Credit_Limit,Num_Credit_Inquiries,Outstanding_Debt,Credit_Utilization_Ratio,Credit_History_Age,Payment_of_Min_Amount,Total_EMI_per_month,Amount_invested_monthly,Monthly_Balance,Num_of_Delayed_Payment
0,23,19114.12,1824.843333,3,3,4,3,11.27,4.0,809.98,26.822620,22 Years and 1 Months,No,49.574949,80.41529543900253,312.49408867943663,7
1,23,19114.12,NaN,3,3,4,-1,11.27,4.0,809.98,31.944960,NaN,No,49.574949,118.28022162236736,284.62916249607184,NaN
2,-500,19114.12,NaN,3,3,4,3,_,4.0,809.98,28.609352,22 Years and 3 Months,No,49.574949,81.699521264648,331.2098628537912,7
3,23,19114.12,NaN,3,3,4,5,6.27,4.0,809.98,31.377862,22 Years and 4 Months,No,49.574949,199.4580743910713,223.45130972736786,4
4,23,19114.12,1824.843333,3,3,4,6,11.27,4.0,809.98,24.797347,22 Years and 5 Months,No,49.574949,41.420153086217326,341.48923103222177,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,25,39628.99,3359.415833,4,7,2,23,11.5,3.0,502.38,34.663572,31 Years and 6 Months,No,35.104023,60.97133255718485,479.866228,7
99996,25,39628.99,3359.415833,4,7,2,18,11.5,3.0,502.38,40.565631,31 Years and 7 Months,No,35.104023,54.18595028760385,496.65161,7
99997,25,39628.99,3359.415833,4,5729,2,27,11.5,3.0,502.38,41.255522,31 Years and 8 Months,No,35.104023,24.02847744864441,516.809083,6
99998,25,39628.99,3359.415833,4,7,2,20,11.5,3.0,502.38,33.638208,31 Years and 9 Months,No,35.104023,251.67258219721603,319.164979,NaN
99999,25,39628.99_,3359.415833,4,7,2,18,11.5,3.0,502.38,34.192463,31 Years and 10 Months,No,35.104023,167.1638651610451,393.673696,6

## Age

In [86]:
print(train_df['Age'].isna().sum())
print(train_df['Age'].isna().mean())
train_df['Age'].info()

0
0.0
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Age
Non-Null Count   Dtype
--------------   -----
100000 non-null  object
dtypes: object(1)
memory usage: 781.4+ KB

In [103]:
print(train_df['Age'].unique().shape)

train_df['Age'].unique()

(1728,)

array([  23, -500,   28, ..., 4808, 2263, 1342])

In [93]:
train_df['Age'] = train_df['Age'].str.replace('_', '')
train_df['Age'] = train_df['Age'].astype(int)

In [97]:
train_df['Age'].describe()

count    100000.000000
mean        110.649700
std         686.244717
min        -500.000000
25%          24.000000
50%          33.000000
75%          42.000000
max        8698.000000
Name: Age, dtype: float64

## Annual Income

In [115]:
fast_feature_description(train_df['Annual_Income'])

0
0.0
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Annual_Income
Non-Null Count   Dtype
--------------   -----
100000 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None

In [108]:
print(train_df['Annual_Income'].unique().shape)

train_df['Annual_Income'].unique()

(13487,)

array(['19114.12', '34847.84', '143162.64', ..., '37188.1', '20002.88',
       '39628.99'], dtype=object)

In [107]:
train_df['Annual_Income'] = train_df['Annual_Income'].str.replace('_', '')

In [110]:
train_df['Annual_Income'] = train_df['Annual_Income'].astype(float)

In [113]:
train_df['Annual_Income'].describe()

count      100,000.00
mean       176,415.70
std      1,429,618.05
min          7,005.93
25%         19,457.50
50%         37,578.61
75%         72,790.92
max     24,198,062.00
Name: Annual_Income, dtype: float64

## Monthly_Inhand_Salary

In [119]:
fast_feature_description(train_df['Monthly_Inhand_Salary'])

---- NULL VALUES --
15002
0.15002
---- INFO --
<class 'pandas.core.series.Series'>
RangeIndex: 100000 entries, 0 to 99999
Series name: Monthly_Inhand_Salary
Non-Null Count  Dtype
--------------  -----
84998 non-null  float64
dtypes: float64(1)
memory usage: 781.4 KB
None
---- Common values --
(13236,)
[1824.84333333           nan 3037.98666667 ... 3097.00833333 1929.90666667
 3359.41583333]

In [123]:
train_df['Monthly_Inhand_Salary'].describe()

count   84,998.00
mean     4,194.17
std      3,183.69
min        303.65
25%      1,625.57
50%      3,093.75
75%      5,957.45
max     15,204.63
Name: Monthly_Inhand_Salary, dtype: float64

In [124]:
train_df['avg_salary'] = train_df['Annual_Income'] / train_df['Monthly_Inhand_Salary']
train_df['avg_salary'].describe()

count   84,998.00
mean        67.24
std        846.10
min          8.09
25%         11.55
50%         12.03
75%         12.55
max     54,110.52
Name: avg_salary, dtype: float64

## Overview

1. Age
- Convert age from strings to int and clean the values with '_'
- Clean outliers and non sense values (thing if we should take them as null values, erros, the best action here is to take the corresponding age of the client in other months)
2. Annual Income:
- Convert the colum from string to float and clean the values with '_'
- It seems accurate, in cleaning check if the monthly salary corresponds to the annual income
3. Monthly Inhand Salary:
- Already float, high null percentage (15%)
- Does not correspond always to the annual income, check for correlation

# Categorical Variables

In [61]:
categorical_variables = ['Occupation','Type_of_Loan','Credit_Mix','Payment_Behaviour']

In [62]:
train_df[categorical_variables]

,Occupation,Type_of_Loan,Credit_Mix,Payment_Behaviour
0,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",_,High_spent_Small_value_payments
1,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Large_value_payments
2,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Medium_value_payments
3,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,Low_spent_Small_value_payments
4,Scientist,"Auto Loan, Credit-Builder Loan, Personal Loan,...",Good,High_spent_Medium_value_payments
...,...,...,...,...
99995,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Large_value_payments
99996,Mechanic,"Auto Loan, and Student Loan",_,High_spent_Medium_value_payments
99997,Mechanic,"Auto Loan, and Student Loan",Good,High_spent_Large_value_payments
99998,Mechanic,"Auto Loan, and Student Loan",Good,Low_spent_Large_value_payments
99999,Mechanic,"Auto Loan, and Student Loan",Good,!@9#%8

In [71]:
remaining_cols = set(train_df.columns) - set(numeric_variables) - set(categorical_variables) - set(ids)
remaining_cols

{'Credit_Score', 'ID', 'Month', 'Name', 'Num_Credit_Card', 'SSN'}